version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'your_database_name'
      MYSQL_USER: 'your_mysql_username'
      MYSQL_PASSWORD: 'your_mysql_password'
      MYSQL_ROOT_PASSWORD: 'your_mysql_root_password'
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: your_database_name
      DB_USER: your_mysql_username
      DB_PASSWORD: your_mysql_password
