version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: loteria
      MYSQL_USER: loteria
      MYSQL_PASSWORD: loteria12345678
    volumes:
      - loteria-db:/var/lib/mysql
  
  loteria:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: loteria
      DB_USER: loteria
      DB_PASSWORD: loteria12345678

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - loteria
      
volumes:
  loteria-db:
