# Generated by Django 4.2 on 2023-04-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=30)),
                ('decha_nacimiento', models.DateField()),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery_app.sorteo')),
            ],
        ),
    ]
