# Generated by Django 4.2 on 2023-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0002_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='decha_nacimiento',
        ),
        migrations.AddField(
            model_name='participante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
