# Generated by Django 4.2 on 2023-04-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0003_remove_participante_decha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ganador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='sorteo_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
