# Generated by Django 4.2 on 2023-04-27 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0004_participante_ganador_sorteo_sorteo_realizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery_app.nacionalidad'),
        ),
    ]
